---
layout: cv
title: "William H. Resume"
format: html
page-layout: full
---

# about me
BYU-I student, Freshman, Computer Scinece Major.

<div id="webaddress">
<a href="isaac@applesdofall.org">isaac@applesdofall.org</a>
</div>

## Currently

Studing code, and improving my code for a personal website and video game i'm working on

### Specialized in

Gaming, Reading, mathamatics, acting, & electrical.

### Research interests

C#, python, Unity Game Engine, Youtube algorithm

## Education

`2016-2019`
__Attended Liberty North Highschool__

`feburary 2020 - August 2020`
__Colorado Denver South mission__

`September 2024 - present day`
__BYU-I Student, Computer science major__

## Awards

`2019`
High school graduation

## Occupation

`2021 - 2023`
__Electritian__
- Austin Electric, trim work
- High Power Electric, Hot checker 

`august 2024 - july 2025`
__BYU-I__, Taylor Building Custodian.

## Contact

- GitHub: [github.com/gamminghobbit](https://github.com/gamminghobbit)  
- LinkedIn: [linkedin.com/in/william-hardy-914702158](https://www.linkedin.com/in/william-hardy-914702158/)  
- Email: willhardy00@gmail.com


<!-- ### Footer

Last updated: May 2013 -->